name: Build and Push to ACR (buildx)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login shipacr55130.azurecr.io \
              --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: shipacr55130.azurecr.io/shipment-delay-api:latest
